[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/getData"
  to = "/.netlify/functions/getData"
  status = 200

[[redirects]]
  from = "/addData"
  to = "/.netlify/functions/addData"
  status = 200

[[redirects]]
  from = "/removeData"
  to = "/.netlify/functions/removeData"
  status = 200

[[redirects]]
  from = "/updateData"
  to = "/.netlify/functions/updateData"
  status = 200

[[redirects]]
  from = "/backupData"
  to = "/.netlify/functions/backupData"
  status = 200

[[redirects]]
  from = "/uploadToGoogleDrive"
  to = "/.netlify/functions/uploadToGoogleDrive"
  status = 200

[[redirects]]
  from = "/restoreFromGoogleDrive"
  to = "/.netlify/functions/restoreFromGoogleDrive"
  status = 200

[[redirects]]
  from = "/restoreFromFile"
  to = "/.netlify/functions/restoreFromFile"
  status = 200

[[redirects]]
  from = "/google-oauth-callback"
  to = "/.netlify/functions/googleOAuthCallback"
  status = 200

[[redirects]]
  from = "/confirmUser"
  to = "/.netlify/functions/confirmUser"
  status = 200
    
[[redirects]]
  from = "/deleteUser"
  to = "/.netlify/functions/deleteUser"
  status = 200

[[redirects]]
  from = "/translateMessage"
  to = "/.netlify/functions/translateMessage"
  status = 200

[[redirects]]
  from = "/ably-auth"
  to = "/.netlify/functions/ably-auth"
  status = 200
