[[redirects]]
  from = "/getData"
  to = "/.netlify/functions/getData"
  status = 200

[[redirects]]
  from = "/addData"
  to = "/.netlify/functions/addData"
  status = 200

[[redirects]]
  from = "/removeData"
  to = "/.netlify/functions/removeData"
  status = 200

[[redirects]]
  from = "/updateData"
  to = "/.netlify/functions/updateData"
  status = 200

[[redirects]]
  from = "/confirmUser"
  to = "/.netlify/functions/confirmUser"
  status = 200
    
[[redirects]]
  from = "/deleteUser"
  to = "/.netlify/functions/deleteUser"
  status = 200

[[redirects]]
  from = "/translateMessage"
  to = "/.netlify/functions/translateMessage"
  status = 200

  [[redirects]]
  from = "/auth-token"
  to = "/.netlify/functions/auth-token"
  status = 200
