[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/backup-downloadUserLists"
  to = "/.netlify/functions/backup-downloadUserLists"
  status = 200

[[redirects]]
  from = "/backup-downloadAllUsers"
  to = "/.netlify/functions/backup-downloadAllUsers"
  status = 200

[[redirects]]
  from = "/backup-restoreUserLists"
  to = "/.netlify/functions/backup-restoreUserLists"
  status = 200

[[redirects]]
  from = "/backup-restoreAllUsers"
  to = "/.netlify/functions/backup-restoreAllUsers"
  status = 200
  
[[redirects]]
  from = "/backup-uploadAllUsersToGoogleDrive"
  to = "/.netlify/functions/backup-uploadAllUsersToGoogleDrive"
  status = 200

[[redirects]]
  from = "/backup-restoreBackupFromGoogleDrive"
  to = "/.netlify/functions/backup-restoreBackupFromGoogleDrive"
  status = 200

[[redirects]]
  from = "/auth-googleOAuthCallback"
  to = "/.netlify/functions/auth-googleOAuthCallback"
  status = 200

[[redirects]]
  from = "/user-confirm"
  to = "/.netlify/functions/user-confirm"
  status = 200
    
[[redirects]]
  from = "/user-delete"
  to = "/.netlify/functions/user-delete"
  status = 200

[[redirects]]
  from = "/translate"
  to = "/.netlify/functions/translate"
  status = 200

[[redirects]]
  from = "/auth-ablyAuth"
  to = "/.netlify/functions/auth-ablyAuth"
  status = 200

  [[redirects]]
  from = "/auth-refreshGoogleToken"
  to = "/.netlify/functions/auth-refreshGoogleToken"
  status = 200